name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: DO
      env:
        IBM_INFO: ${{secrets.IBM_INFO}}
        COMMON_PASSWORD: ${{secrets.COMMON_PASSWORD}}
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
        IBM_ACCOUNT=`echo $IBM_INFO | jq .IBM_ACCOUNT -r`
        IBM_APP_NAME=`echo $IBM_INFO | jq .IBM_APP_NAME -r`
        REGION_NUM=`echo $IBM_INFO | jq .REGION_NUM -r`
        RESOURSE_ID=`echo $IBM_INFO | jq .RESOURSE_ID -r`
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $COMMON_PASSWORD
        $REGION_NUM
        no
        EOF
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install <<EOF
        n
        EOF
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME"
