name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      env:
        IBM_INFO: ${{secrets.IBM_INFO}}
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
        IBM_ACCOUNT=`echo $IBM_INFO | jq .IBM_ACCOUNT -r`
    - name: Login IBM Cloud
      env:
        IBM_INFO: ${{secrets.IBM_INFO}}
      run: |
        IBM_ACCOUNT=`echo $IBM_INFO | jq .IBM_ACCOUNT -r`
        echo $IBM_ACCOUNT
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $IBM_PASSWORD
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME"
