name: Checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Python
      run: |
        sudo apt update 
        sudo apt install python3

    - name: Install Chrome 
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' 
        sudo apt update 
        sudo apt install google-chrome-stable 
        sudo wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip 
        sudo unzip chromedriver_linux64.zip 
        sudo mv chromedriver /usr/bin/chromedriver 
        sudo chown root:root /usr/bin/chromedriver 
        sudo chmod +x /usr/bin/chromedriver 
        google-chrome -version 
        chromedriver -version
        whereis chromedriver
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
    
    - name: SMZDMCheckin
      env:
        SMZDM_COOKIES: ${{ secrets.SMZDM_COOKIES }}
      run: |
        python3 smzdm.py

    - name: tianyi
      env:
        SMZDM_COOKIES: ${{ secrets.TIANYI_USERS }}
      run: |
        random_time=$(($RANDOM % 45))
        echo "等待 ${random_time} 分钟后开始签到"
        for((i=1;i<=${random_time};i++));  
        do
        echo "倒计时:剩余 $[${random_time}-$i] 分钟"
        sleep 1m
        done

        python3 tianyi.py