name: Checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update 
        sudo apt install python3

    - name: Install Chrome 
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' 
        sudo apt update 
        sudo apt install google-chrome-stable 
        sudo wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip 
        sudo unzip chromedriver_linux64.zip 
        sudo mv chromedriver /usr/bin/chromedriver 
        sudo chown root:root /usr/bin/chromedriver 
        sudo chmod +x /usr/bin/chromedriver 
        google-chrome -version 
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
    
    - name: SMZDMCheckin
      run: |
        python3 smzdm.py <<EOF
        ${{ secrets.SMZDM_COOKIES }}
        EOF

    - name: C189Checkin
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        
        user_list=()
        pwd_list=()
        IFS=" "
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done
        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}
        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi

        random_time=$(($RANDOM % 45))
        echo "等待 ${random_time} 分钟后开始签到"
        for((i=1;i<=${random_time};i++));  
        do
        echo "倒计时:剩余 $[${random_time}-$i] 分钟"
        sleep 1m
        done

        for ((i=0;i<$user_num;i++))
        do
        python3 C189Checkin.py <<EOF
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done