name: Checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: remove git-lfs
      shell: bash
      run: |
        sudo rm /etc/apt/sources.list.d/github_git-lfs.list 
        sudo rm /etc/apt/sources.list.d/github_git-lfs.list.save
                
    - name: Install Python
      run: |
        sudo apt update 
        sudo apt install python3

    - name: Install Chrome 
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' 
        sudo apt update 
        sudo wget http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-browser_73.0.3683.103-0ubuntu1_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb --fix-missing; apt-get -fy install
        sudo wget https://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_linux64.zip 
        sudo unzip chromedriver_linux64.zip 
        sudo mv chromedriver /usr/bin/chromedriver 
        sudo chown root:root /usr/bin/chromedriver 
        sudo chmod +x /usr/bin/chromedriver 
        chromedriver -version
        whereis chromedriver
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
    
    - name: SMZDMCheckin
      env:
        SMZDM_COOKIES: ${{ secrets.SMZDM_COOKIES }}
      run: |
        python3 smzdm.py

    - name: tianyi
      env:
        TIANYI_USERS: ${{ secrets.TIANYI_USERS }}
      run: |
        random_time=$(($RANDOM % 45))
        echo "等待 ${random_time} 分钟后开始签到"
        for((i=1;i<=${random_time};i++));  
        do
        echo "倒计时:剩余 $[${random_time}-$i] 分钟"
        sleep 1m
        done

        python3 tianyi.py

